#!/bin/bash

function csgosetup() {
    sudo dpkg --add-architecture i386
    sudo add-apt-repository multiverse
    sudo apt update && sudo apt upgrade
    sudo apt install steamcmd
    sudo adduser --gecos "" --disabled-login --disabled-password csgo
}

function csgoinstall() {
    steamcmd +force_install_dir $SRCDS_DIR +login anonymous +app_update 740 validate +quit
}

function csgoupdate() {
    steamcmd +force_install_dir $SRCDS_DIR +login anonymous +app_update 740 +quit
}

function csgocopyfiles() {
    cp /home/csgo/csgo-linux/autoexec.cfg $SRCDS_DIR/csgo/cfg/autoexec.cfg
    cp /home/csgo/csgo-linux/server.cfg $SRCDS_DIR/csgo/cfg/server.cfg
    cp /home/csgo/csgo-linux/aliases.cfg $SRCDS_DIR/csgo/cfg/aliases.cfg
    cp /home/csgo/csgo-linux/secrets.cfg $SRCDS_DIR/csgo/cfg/secrets.cfg
    cp /home/csgo/csgo-linux/gamemode_competitive_server.cfg $SRCDS_DIR/csgo/cfg/gamemode_competitive_server.cfg
    chmod +x $SRCDS_DIR/csgo/cfg/autoexec.cfg
    chmod +x $SRCDS_DIR/csgo/cfg/server.cfg
    chmod +x $SRCDS_DIR/csgo/cfg/aliases.cfg
    chmod +x $SRCDS_DIR/csgo/cfg/secrets.cfg
    chomd +x $SRCDS_DIR/csgo/cfg/gamemode_competitive_server.cfg
}

function csgo() {
    $SRCDS_DIR/srcds_run -game csgo -tickrate 128 -console -usercon +game_type 0 +game_mode 1 +mapgroup mg_active +map de_dust2 +sv_setsteamaccount $CSGO_GSLT -net_port_try 1
}
