#!/bin/bash

function setup() {
    sudo dpkg --add-architecture i386
    sudo add-apt-repository multiverse
    sudo apt update && sudo apt upgrade
    sudo apt install steamcmd
    #adduser csgo
}

function install() {
    su - csgo
    steamcmd +force_install_dir $SRCDS_DIR +login anonymous +app_update 740 validate +quit
}

function update() {
    steamcmd +force_install_dir $SRCDS_DIR +login anonymous +app_update 740 +quit
}